#!/bin/bash

### BEGIN INIT INFO
# Provides:          firstrun
# Required-Start:    $all
# Required-Stop:
# Should-Start:      
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to run when first starting
# Description:       Something needs to be done when  is
#                    starting at first time.
#                    regenerate ssh host key
### END INIT INFO

N=/etc/init.d/firstrun

set -e

do_expand_rootfs(){
        device="/dev/"$(lsblk -idn -o NAME | grep mmc)
		PARTITIONS=$(($(fdisk -l $device | grep $device | wc -l)-1))
		((echo d; echo $PARTITIONS; echo n; echo p; echo ; echo ; echo ; echo w;) | fdisk $device)>/dev/null
return 0
}

case "$1" in
  start)
		reboot=false
		echo "System will reboot automatically. Please wait!" >/dev/tty1
		echo "" >/dev/tty1

		echo -e "[\e[0;32m ok \x1B[0m] SSH keys recreation. One moment please" >/dev/tty1
		rm -f /etc/ssh/ssh_host*
		dpkg-reconfigure openssh-server
		set +e
        echo "Expanding rootfs..." >/dev/tty1
        if do_expand_rootfs;then
                echo "Expanding rootfs success, rebooting automatically." >/dev/tty1
				update-rc.d resize2fs defaults >/dev/null 2>&1
                reboot=true
        else
                echo "Expanding rootfs has failed, see log files." >/dev/tty1
        fi
		update-rc.d -f firstrun remove >/dev/null 2>&1
        rm /etc/init/ssh.override
        rm /etc/init/lightdm.override
		if $reboot;then
			/sbin/reboot
		fi
        ;;
  *)
        echo "Usage: $N {start}" >&2
        exit 1
        ;;
esac

exit 0
