#!/bin/bash

### BEGIN INIT INFO
# Provides:          firstrun
# Required-Start:    $all
# Required-Stop:
# Should-Start:      
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to run when first starting
# Description:       Something needs to be done when  is
#                    starting at first time.
#                    regenerate ssh host key
### END INIT INFO

N=/etc/init.d/firstrun

set -e

do_expand_rootfs(){
  device="/dev/"$(lsblk -idn -o NAME | grep mmc)
  rootpart=$(df / --output=source | tail -n1)
  PARTITIONS=$(($(fdisk -l $device | grep $device | wc -l)-1))
  
  echo Editing the partition table... >/dev/ttymxc1
  ( (echo d; echo $PARTITIONS; echo n; echo p; echo ; echo ; echo ; echo w; ) | 
    fdisk $device )>/dev/null
  sync
  
  echo Probing the partition table... >/dev/ttymxc1
  partx -u ${rootpart} >/dev/ttymxc1 || return $?
  
  echo Resizing the partition... >/dev/ttymxc1 
  resize2fs ${rootpart}  >/dev/ttymxc1 || return $?
}

case "$1" in
  start)
    reboot=false

    echo -e "SSH keys recreation. One moment please" >/dev/ttymxc1
    rm -f /etc/ssh/ssh_host*
    dpkg-reconfigure openssh-server >/dev/ttymxc1
    set +e
    
    echo "Expanding rootfs..." >/dev/ttymxc1

    if do_expand_rootfs ;
    then
      echo "Expanding partition success" >/dev/ttymxc1
    else
      echo "Expanding rootfs has failed, see log files. Error code: $?" >/dev/ttymxc1
    fi

    update-rc.d -f firstrun remove >/dev/null 2>&1 >/dev/ttymxc1
    
    rm /etc/init/ssh.override
    service ssh start
    
    if `rm /etc/init/lightdm.override 2>/dev/null`
      then
      service lightdm start
    fi
  ;;
  
  *)
    echo "Usage: $N {start}" >&2
    exit 1
  ;;
esac
  
exit 0
